### ISSUE TITLE
[Bug]: Error in App Routing

### ISSUE THREAD

**Issue by guesung** [toss/use-funnel#41]
### Package Scope

@use-funnel/next

### Bug description

In App Router, we're encountering an error as shown in the image below:

<img width="990" alt="Error in App Router" src="https://github.com/user-attachments/assets/e8ab8bdf-c240-4940-a938-19a410cbf467">

This issue appears to stem from the use of `useRouter` from `next/router` within useFunnel. However, in App Router, we cannot use `useRouter` from `next/router`. Instead, we need to use `useRouter` from `next/navigation`. [ref](https://nextjs.org/docs/messages/next-router-not-mounted)

### To Reproduce

Next.js13 + App Routing

You can test and check in here [repository](https://github.com/guesung/guesung-world/tree/master/packages/playground/use-funnel)

### Possible Solution

To address this, I propose we separate Next.js support into two distinct packages: one for Pages Router and another for App Router. 

If it's alright with you, may I proceed with this change? I'm ready to work on it quickly and efficiently! Thank you.

**Comment by wontory** [comment]
You should use @use-funnel/browser for app router.

**Comment by guesung** [comment]
Oh I missed that. Thank you @wontory
