### ISSUE TITLE
[Feature]: Remove condition `K extends keyof TBase ? never : never` in CompareKeys Type

### ISSUE THREAD

**Issue by L2HYUNN** [toss/use-funnel#55]
### Package Scope

@use-funnel/core

### Description

Hello!

I’m very interested in the use funnel library, and while exploring the code to understand its internal structure, I came across the following code and had a few questions about it.

```ts
export type RequiredCompareKeys<TBase, TResult> = {
  [K in keyof TBase | keyof TResult]: K extends keyof TResult
    ? K extends keyof TBase
      ? TBase[K] extends TResult[K]
        ? never
        : K
      : undefined extends TResult[K]
        ? never
        : K
    : K extends keyof TBase
      ? never
      : never;
}[keyof TBase | keyof TResult];

```

It seems that the following line:

```ts
K extends keyof TBase ? never : never;
```

could be simplified to just `never` as shown below. Is there a specific reason for keeping this condition?

```ts
type RequiredCompareKeys<TBase, TResult> = {
  [K in keyof TBase | keyof TResult]: K extends keyof TResult
    ? K extends keyof TBase
      ? TBase[K] extends TResult[K]
        ? never
        : K
      : undefined extends TResult[K]
      ? never
      : K
    : never;
}[keyof TBase | keyof TResult];
```

If this simplification looks good to you, I’d be happy to open a PR.

**Comment by minuukang** [comment]
Thanks to provide a type issue! your idea is should be remove and improve at #56 PR. and i will add you co-author at that PR.
