### ISSUE TITLE
[Bug]: Copying the funnel code example from README.md results in a type error.

### ISSUE THREAD

**Issue by Lennon57** [toss/use-funnel#60]
### Package Scope

@use-funnel/react-router-dom

### Bug description

Copying the code as is from the README.md results in a type error in `funnel.Render` within `SelectSchool`.

<img width="1453" alt="스크린샷 2024-09-23 오전 12 46 24" src="https://github.com/user-attachments/assets/3ea0cd14-dfba-40a1-95cb-606704835221">

### Expected behavior

The similar `SelectEmployee` component does not produce this error and should behave the same way.

### Possible Solution

This issue may be resolved by using the `prev` property in the second argument of `history.push`, which will also help maintain consistency with the convention.

**Comment by minuukang** [comment]
Thank you! i'll approve and merge that.
