### ISSUE TITLE
[Bug]: 네비게이션에 첫 번째 히스토리가 없을 경우, 첫 스텝의 오버레이에서 뒤로가기 불가능

### ISSUE THREAD

**Issue by CodePsy-2001** [toss/use-funnel#77]
### Package Scope

@use-funnel/react-navigation-native

### Bug description

네비게이션에 첫 번째 히스토리가 없을 경우
(예: 앱을 켜는 즉시 렌더되는 index.tsx 에서 곧바로 Funnel을 그릴 경우, Redirect 처리 직후 signup Funnel을 그릴 경우 등)
첫 스텝에서 오버레이를 사용 시 overlay.close(), router.back() 및 네이티브 back버튼 등 '뒤로가기'와 관련된 동작들이 전부 동작하지 않습니다.

반면,
- 다른 페이지에서 expo-router Link를 누르거나 expoRouter.push(), navigation.navigate(), navigation.push() 등을 통해 첫 번째 히스토리를 쌓은 뒤 Funnel을 그릴 경우
- Funnel의 첫 번째 스텝이 아닌 스텝에서 오버레이를 사용할 경우
오버레이의 '뒤로가기'와 관련된 동작들이 정상 작동합니다.

expo 51, react-native 0.74, expo-router 3.5.24, @react-navigation/native 6.0.2 환경에서 테스트되었습니다.
테스트에 사용한 기기는 Android GalaxyS23U (실물 디바이스) 입니다.

오류 원인을 파악하기 위해 다음 작업을 제안합니다.
- 테스트케이스에 첫 번째 스텝에서 overlay를 렌더하는 경우를 추가해주세요
- overlay 및 overlay.close() 관련 동작이 코드에 잘 드러나지 않습니다. 좀 더 명시적으로 작성해야 합니다.

### Expected behavior

기존 히스토리 및 overlay 여부와 상관없이 Funnel의 back이 항상 작동해야 함.

### To Reproduce

네비게이션에 첫 번째 히스토리가 없을 경우
(예: 앱을 켜는 즉시 렌더되는 index.tsx 에서 곧바로 Funnel을 그릴 경우, Redirect 처리 직후 signup Funnel을 그릴 경우 등)
첫 스텝에서 오버레이를 사용 시 overlay.close(), router.back() 및 네이티브 back버튼 등 '뒤로가기'와 관련된 동작들이 전부 동작하지 않습니다.

### Possible Solution

예상되는 원인은 src/index.ts 코드 143번째 줄의 if(route.canGoBack()) 조건에 걸리기 때문입니다.
이 경우 간단한 console.log() 로 확인할 수 있습니다.

첫 번째 히스토리가 없는 특이한 경우를 처리하기 위해, 단순 canGoBack() 에 더해 다른 방법을 사용해야 할 것으로 보입니다.
예를 들어, go 함수 내부에서 isOverlay를 체크할 수 있습니다.

### etc.

3일 내에 오류를 재현 가능한 테스트코드를 Pull Request 하겠습니다.

**Comment by CodePsy-2001** [comment]
https://github.com/toss/use-funnel/pull/79

오류를 재현 가능한 테스트코드입니다. 동일 PR 안에서 오류 수정도 해보겠습니다.

**Comment by minuukang** [comment]
이슈 등록 감사합니다! 코멘트 남겨놨어요.

**Comment by minuukang** [comment]
This issue is fix at `@use-funnel/react-nativation-native@0.0.8`. Thanks for your issue and contribute!
