### ISSUE TITLE
[Bug]: Is showing all steps at once the intended behavior?

### ISSUE THREAD

**Issue by fe-dudu** [toss/use-funnel#86]
### Package Scope

@use-funnel/core, @use-funnel/react-router-dom

### Bug description

https://github.com/user-attachments/assets/748971ed-f7b4-4bbe-be46-fb4145c3a42b

In the third step, only the second step should be displayed under the Dialog, but the first step is also visible simultaneously. Is showing all steps at once the intended behavior?

https://use-funnel-ex.vercel.app
https://github.com/fe-dudu/use-funnel-ex

**Comment by minuukang** [comment]
No, the "passwordStep" should be only visibled at overlay step "completeStep".

I'll check this out!

**Comment by minuukang** [comment]
It has a bug when overlay step before step has event step (at example "passwordStep").

I'll fix it soon

**Comment by minuukang** [comment]
This issue is fix at `@use-funnel/react-router-dom@0.0.8`! Thanks to find issue 🙇🏽
