### ISSUE TITLE
[Bug]: Page containing <funnel.Render /> unmounts after window.history.back() or browser back navigation.

### ISSUE THREAD

**Issue by mitchell-up** [toss/use-funnel#90]
### Package Scope

@use-funnel/browser

### Bug description

Given: A main funnel with 3 steps and a sub-funnel with 2 steps

1. Start from '/some' page
2. Navigate to a page containing both funnels (Main step 1, Sub step 1)
3. Move forward in the sub-funnel (Main step 1, Sub step 2)
4. Move forward to Main step (Main Step2)
5. Click browser back or window.history.back() ('/some')

### Expected behavior

Browser back navigation should return to the previous funnel step (Main step 1, Sub step 2) instead of exiting to '/some'.

While `window.location` shows the correct address (Main step 1, Sub step 2), Next.js unexpectedly renders the '/some' page instead.

### To Reproduce

To reproduce the navigation back error, please check the Stackblitz example below:
https://stackblitz.com/edit/stackblitz-starters-djxeri?file=app%2Fpage.tsx

**Comment by minuukang** [comment]
This issue is fixed at `@use-funnel/browser@0.0.10`. Thanks for your contribute!
