### ISSUE TITLE
[Bug]: Duplicated sub funnel ids may cause incorrect step rendering.

### ISSUE THREAD

**Issue by mitchell-up** [toss/use-funnel#94]
### Package Scope

@use-funnel/browser

### Bug description

Two identical sub-funnels within a main funnel cause step persistence issues.

1. Initial state: Main-A, Sub-A
2. After Sub step: Main-A, Sub-B
3. After Main step: Main-B, Sub-B (incorrect)

### Expected behavior

No. 3 should show: Main-B, Sub-A

### Possible Solution

That's because `window.history.state` of first sub funnel is alive even after that sub funnel has unmounted.

**Comment by minuukang** [comment]
This issue is same thing from (#85 )

Since all packages are affected, let's do a better job of thinking about it.

**Comment by minuukang** [comment]
This issue is solved @use-funnel/browser@0.0.11 version at https://github.com/toss/use-funnel/pull/97.

Based on what you posted, I've listed you as a co-author on that PR.

Thanks to contribute!
